services:
  - type: web
    name: osiyo-trade-biznes-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: SUPPORT_GROUP_ID
        sync: false
      - key: PORT
        value: 10000
      - key: DATA_DIR
        value: ./data

